---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - "{{ config_file }}"

  tasks:
    - name: get my public IP
      ipify_facts:

    - name: update DNS zone
      route53:
        command: create
        zone: "{{ item.0.zone }}"
        record: "{{ item.1 }}"
        type: A
        ttl: 60
        value: "{{ ipify_public_ip }}"
        overwrite: yes
      with_subelements:
        - "{{ route53_zones }}"
        - hostnames
